 name:  New Students Api Pipeline

on:
  push:
    branches:
      - main

jobs:

  hello:
    name: "Hello World"
    runs-on:  ubuntu-lastest
    steps:
      - name: Say Hello
      run:  echo "Hello world"