name:  New Students Api Pipeline

on:
  push:
    branches:
      - master

jobs:
  hello:
    name: "Show our code"
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      NAME: ${{secrets.NAME}}
      WORLD: "Earth"
      PORT: 5000
    steps:
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - name: Show the index.ts
        run: cat api/index.ts
      - name: Show enviroment
        run: echo "You are in $NODE_ENV enviroment"
      - name: Say hello
        run: echo "Hello $NAME and $WORLD"

  verify: 
    name: "Verify node version"
    runs-on: ubuntu-latest
    steps:  
      - name: Verify node version
        run: node -v

  directory: 
    name: "Enter in directory"
    runs-on: ubuntu-latest 
    steps:  
      - name: Enter in directory
        run: cd api/
      - name: Show the directory
        run: ls

  install: 
    name: "Config application"
    runs-on: ubuntu-latest 
    steps:   
      - name: Show the directory
        run: ls
      - name: Install dependencies
        run: npm install

  test: 
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:  
      - name: Run tests
        run: npm run test