name:  New Students Api Pipeline

on:
  push:
    branches:
      - master


defaults:
  run:
    working-directory: ./api
    
jobs:

  hello:
    name: "Show our code"
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      NAME: ${{secrets.NAME}}
      WORLD: "Earth"
      PORT: 5000
    steps:
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - name: Show the index.ts
        run: cat index.ts
      - name: Show enviroment
        run: echo "You are in $NODE_ENV enviroment"
      - name: Say hello
        run: echo "Hello $NAME and $WORLD"

  verify: 
    name: "Verify node version"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ../
    steps:
      - uses: actions/checkout@v2
      - name: Verify node version
        run: node -v 

  install: 
    name: "Config application"
    runs-on: ubuntu-latest 
    steps:   
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

  test: 
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  build: 
    name: "Run build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Show dist content
        run: ls ./dist

  docker :
    name: "See docker"
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Show the directory
        run: ls
      - uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thestudentsapi"
          email: ${{secrets.HEROKU_EMAIL}} 
          dockerfile_directory: ./api
          dockerfile_name: Dockerfile
          process_type: web
      - name: See docker version
        run: docker version 
      - name: Build Container
        run: docker-compose up --build -d
      - name: See containers
        run: docker ps
